// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFirst.Test
{
    public partial interface ILibraryDbContextProcedures
    {
        Task<List<SP_BOOK_CATEGORYResult>> SP_BOOK_CATEGORYAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
