// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFirst.Test
{
    public partial class LibraryDbContext
    {
        private ILibraryDbContextProcedures _procedures;

        public virtual ILibraryDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LibraryDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ILibraryDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class LibraryDbContextProcedures : ILibraryDbContextProcedures
    {
        private readonly LibraryDbContext _context;

        public LibraryDbContextProcedures(LibraryDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_BOOK_CATEGORYResult>> SP_BOOK_CATEGORYAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_BOOK_CATEGORYResult>("EXEC @returnValue = [dbo].[SP_BOOK_CATEGORY]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
