// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DatabaseFirst.Models;

namespace DatabaseFirst.Test
{
    public partial class LibraryDbContext
    {

        [DbFunction("GET_CATEGORY_BOOKS", "dbo")]
        public IQueryable<GET_CATEGORY_BOOKSResult> GET_CATEGORY_BOOKS(string CATEGORY_NAME)
        {
            return FromExpression(() => GET_CATEGORY_BOOKS(CATEGORY_NAME));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GET_CATEGORY_BOOKSResult>().HasNoKey();
        }
    }
}
