// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Test.Configurations
{
    public partial class AlexAndCairoEmpConfiguration : IEntityTypeConfiguration<AlexAndCairoEmp>
    {
        public void Configure(EntityTypeBuilder<AlexAndCairoEmp> entity)
        {
            entity.ToView("AlexAndCairoEmp");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AlexAndCairoEmp> entity);
    }
}
