// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[Keyless]
public partial class AlexAndCairoEmp
{
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Fname { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string Lname { get; set; } = null!;

    [Column("phone")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Phone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column("DOB")]
    public DateOnly? Dob { get; set; }

    public int? Salary { get; set; }

    public int? Bouns { get; set; }

    [Column("Super_id")]
    public int? SuperId { get; set; }

    [Column("Floor_no")]
    public int? FloorNo { get; set; }
}