// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

public partial class Book
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; } = null!;

    [Column("Cat_id")]
    public int CatId { get; set; }

    [Column("Publisher_id")]
    public int PublisherId { get; set; }

    [Column("Shelf_code")]
    [StringLength(3)]
    [Unicode(false)]
    public string ShelfCode { get; set; } = null!;

    public int? PublishedYear { get; set; }

    [ForeignKey("CatId")]
    [InverseProperty("Book")]
    public virtual Category Cat { get; set; } = null!;

    [ForeignKey("BookId")]
    [InverseProperty("Book")]
    public virtual ICollection<Author> Author { get; set; } = new List<Author>();
}