// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

public partial class Category
{
    [Key]
    public int Id { get; set; }

    [Column("Cat_name")]
    [StringLength(50)]
    [Unicode(false)]
    public string CatName { get; set; } = null!;

    [InverseProperty("Cat")]
    public virtual ICollection<Book> Book { get; set; } = new List<Book>();
}