// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatabaseFirst.Models
{
    public partial class SP_BOOK_CATEGORYResult
    {
        [StringLength(50)]
        public string Cat_name { get; set; } = default!;
        [Column("Count Of Books")]
        public int? CountOfBooks { get; set; }
    }
}
